name: Build and Publish

on:
  push:
    tags:
      - *

jobs:
  build-and-publish-container-image:
    name: Build and publish container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Sign in to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}